# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibrationUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1401, 994)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.x_plus = QtWidgets.QPushButton(self.centralwidget)
        self.x_plus.setGeometry(QtCore.QRect(220, 760, 113, 32))
        self.x_plus.setObjectName("x_plus")
        self.x_minus = QtWidgets.QPushButton(self.centralwidget)
        self.x_minus.setGeometry(QtCore.QRect(350, 760, 113, 32))
        self.x_minus.setObjectName("x_minus")
        self.y_plus = QtWidgets.QPushButton(self.centralwidget)
        self.y_plus.setGeometry(QtCore.QRect(220, 810, 113, 32))
        self.y_plus.setObjectName("y_plus")
        self.y_minus = QtWidgets.QPushButton(self.centralwidget)
        self.y_minus.setGeometry(QtCore.QRect(350, 810, 113, 32))
        self.y_minus.setObjectName("y_minus")
        self.z_plus = QtWidgets.QPushButton(self.centralwidget)
        self.z_plus.setGeometry(QtCore.QRect(220, 860, 113, 32))
        self.z_plus.setObjectName("z_plus")
        self.z_minus = QtWidgets.QPushButton(self.centralwidget)
        self.z_minus.setGeometry(QtCore.QRect(350, 860, 113, 32))
        self.z_minus.setObjectName("z_minus")
        self.rx_plus = QtWidgets.QPushButton(self.centralwidget)
        self.rx_plus.setGeometry(QtCore.QRect(520, 760, 113, 32))
        self.rx_plus.setObjectName("rx_plus")
        self.rx_minus = QtWidgets.QPushButton(self.centralwidget)
        self.rx_minus.setGeometry(QtCore.QRect(650, 760, 113, 32))
        self.rx_minus.setObjectName("rx_minus")
        self.ry_plus = QtWidgets.QPushButton(self.centralwidget)
        self.ry_plus.setGeometry(QtCore.QRect(520, 810, 113, 32))
        self.ry_plus.setObjectName("ry_plus")
        self.ry_minus = QtWidgets.QPushButton(self.centralwidget)
        self.ry_minus.setGeometry(QtCore.QRect(650, 810, 113, 32))
        self.ry_minus.setObjectName("ry_minus")
        self.rz_plus = QtWidgets.QPushButton(self.centralwidget)
        self.rz_plus.setGeometry(QtCore.QRect(520, 860, 113, 32))
        self.rz_plus.setObjectName("rz_plus")
        self.rz_minus = QtWidgets.QPushButton(self.centralwidget)
        self.rz_minus.setGeometry(QtCore.QRect(650, 860, 113, 32))
        self.rz_minus.setObjectName("rz_minus")
        self.image_window = QtWidgets.QLabel(self.centralwidget)
        self.image_window.setGeometry(QtCore.QRect(60, 20, 1280, 720))
        self.image_window.setText("")
        self.image_window.setObjectName("image_window")
        self.x_curret = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.x_curret.setGeometry(QtCore.QRect(830, 770, 81, 31))
        self.x_curret.setObjectName("x_curret")
        self.y_current = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.y_current.setGeometry(QtCore.QRect(950, 770, 81, 31))
        self.y_current.setObjectName("y_current")
        self.z_current = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.z_current.setGeometry(QtCore.QRect(1070, 770, 81, 31))
        self.z_current.setObjectName("z_current")
        self.rx_current = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.rx_current.setGeometry(QtCore.QRect(830, 840, 81, 31))
        self.rx_current.setObjectName("rx_current")
        self.ry_current = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ry_current.setGeometry(QtCore.QRect(950, 840, 81, 31))
        self.ry_current.setObjectName("ry_current")
        self.rz_current = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.rz_current.setGeometry(QtCore.QRect(1070, 840, 81, 31))
        self.rz_current.setObjectName("rz_current")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(810, 780, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(930, 780, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1050, 780, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(800, 850, 21, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(920, 850, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1040, 850, 21, 16))
        self.label_7.setObjectName("label_7")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(920, 910, 113, 32))
        self.save_btn.setObjectName("save_btn")
        self.gripper_on = QtWidgets.QPushButton(self.centralwidget)
        self.gripper_on.setGeometry(QtCore.QRect(280, 910, 113, 32))
        self.gripper_on.setObjectName("gripper_on")
        self.gripper_off = QtWidgets.QPushButton(self.centralwidget)
        self.gripper_off.setGeometry(QtCore.QRect(580, 910, 113, 32))
        self.gripper_off.setObjectName("gripper_off")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1401, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.x_plus, self.x_minus)
        MainWindow.setTabOrder(self.x_minus, self.y_plus)
        MainWindow.setTabOrder(self.y_plus, self.y_minus)
        MainWindow.setTabOrder(self.y_minus, self.z_plus)
        MainWindow.setTabOrder(self.z_plus, self.z_minus)
        MainWindow.setTabOrder(self.z_minus, self.rx_plus)
        MainWindow.setTabOrder(self.rx_plus, self.rx_minus)
        MainWindow.setTabOrder(self.rx_minus, self.ry_plus)
        MainWindow.setTabOrder(self.ry_plus, self.ry_minus)
        MainWindow.setTabOrder(self.ry_minus, self.rz_plus)
        MainWindow.setTabOrder(self.rz_plus, self.rz_minus)
        MainWindow.setTabOrder(self.rz_minus, self.x_curret)
        MainWindow.setTabOrder(self.x_curret, self.y_current)
        MainWindow.setTabOrder(self.y_current, self.z_current)
        MainWindow.setTabOrder(self.z_current, self.rx_current)
        MainWindow.setTabOrder(self.rx_current, self.ry_current)
        MainWindow.setTabOrder(self.ry_current, self.rz_current)
        MainWindow.setTabOrder(self.rz_current, self.save_btn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.x_plus.setText(_translate("MainWindow", "X+"))
        self.x_minus.setText(_translate("MainWindow", "X-"))
        self.y_plus.setText(_translate("MainWindow", "Y+"))
        self.y_minus.setText(_translate("MainWindow", "Y-"))
        self.z_plus.setText(_translate("MainWindow", "Z+"))
        self.z_minus.setText(_translate("MainWindow", "Z-"))
        self.rx_plus.setText(_translate("MainWindow", "Rx+"))
        self.rx_minus.setText(_translate("MainWindow", "Rx-"))
        self.ry_plus.setText(_translate("MainWindow", "Ry+"))
        self.ry_minus.setText(_translate("MainWindow", "Ry-"))
        self.rz_plus.setText(_translate("MainWindow", "Rz+"))
        self.rz_minus.setText(_translate("MainWindow", "Rz-"))
        self.label_2.setText(_translate("MainWindow", "X:"))
        self.label_3.setText(_translate("MainWindow", "Y:"))
        self.label_4.setText(_translate("MainWindow", "Z:"))
        self.label_5.setText(_translate("MainWindow", "Rx:"))
        self.label_6.setText(_translate("MainWindow", "Ry:"))
        self.label_7.setText(_translate("MainWindow", "Rz:"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.gripper_on.setText(_translate("MainWindow", "Gripper on"))
        self.gripper_off.setText(_translate("MainWindow", "Gripper off"))


